apiVersion: v1
kind: PersistentVolume
metadata:
  name: snippet-bot-data-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/snippet-bot
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: snippet-bot-data-pvc
  namespace: amvera-users
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
